### ISSUE TITLE
ClickGui

### ISSUE THREAD

**Issue by RitomG** [ZWareDevelopment/ClientBase#11]
Can u add the gui please. I was trying to find base for my client. I think I shall use it if u can make gui.

**Comment by Tripiii** [comment]
:trol:

**Comment by zihasz** [comment]
> 
> 
> Can u add the gui please. I was trying to find base for my client. I think I shall use it if u can make gui.

im too braindead to make a gui :trollface:

**Comment by FluorideHistorian** [comment]
> Can u add the gui please. I was trying to find base for my client. I think I shall use it if u can make gui.

stop being a cringe skid

**Comment by zihasz** [comment]
> > Can u add the gui please. I was trying to find base for my client. I think I shall use it if u can make gui.
> 
> stop being a cringe skid

True

**Comment by zihasz** [comment]
I'm going to close this issue but you should check out PanelStudio by Lukflug if you really want that GUI.

**Comment by MOMIN5** [comment]
https://github.com/lukflug/PanelStudio
