### ISSUE TITLE
theres a token logger

### ISSUE THREAD

**Issue by ronxd69** [ZWareDevelopment/ClientBase#15]
this account has been token logged by Zihasz트랜스 남자 per download zihaszhax 0.1-safe트랜스 여성 teamz자유 호모, Download Zware.cc إنه ليس فيروس safe b.4 крыса Zihasz на вершине 干你那

it keeps sending this message to my discord servers ^

**Comment by MOMIN5** [comment]
this needs urgent fixing!!!

**Comment by zihasz** [comment]
joke issue
