### ISSUE TITLE
build

### ISSUE THREAD

**Issue by Skarlord991** [ZWareDevelopment/ClientBase#8]
* What went wrong:
Could not resolve all files for configuration ':forgeGradleMc'.
> Could not find forgeSrc.jar (net.minecraftforge:forgeSrc:1.12.2-14.23.5.2768-PROJECT(ClientBase)).
  Searched in the following locations:
      https://files.minecraftforge.net/maven/net/minecraftforge/forgeSrc/1.12.2-14.23.5.2768-PROJECT(ClientBase)/forgeSrc-1.12.2-14.23.5.2768-PROJECT(ClientBase).jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.9/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 3s
5 actionable tasks: 3 executed, 2 up-to-date

**Comment by zihasz** [comment]
known issue with forge

**Comment by Skarlord991** [comment]
and what how can i fix it?

**Comment by zihasz** [comment]
its a problem on forges side so you cant (or atleast i think)

**Comment by MOMIN5** [comment]
@Skarlord991 did you do gradlew setupDecompWorkspace?

**Comment by Skarlord991** [comment]
it works with gradlew setupDecompWorkspace.Thank you

**Comment by MOMIN5** [comment]
@zihasz look lol

**Comment by zihasz** [comment]
@MOMIN5 oh im retarded
